extends: default

rules:
  document-start: disable
  truthy: disable
  comments-indentation: disable
  line-length:
    max: 120
    allow-non-breakable-words: true
    allow-non-breakable-inline-mappings: true
